DELETE FROM SYS_USER_ROLE WHERE USER_ID = 1 AND ROLE_ID = 1;
DELETE FROM SYS_ROLE_PERMISSION WHERE ROLE_ID = 1 AND PERMISSION_ID = 100001;
DELETE FROM SYS_ROLE_PERMISSION WHERE ROLE_ID = 1 AND PERMISSION_ID = 100002;
DELETE FROM SYS_ROLE_PERMISSION WHERE ROLE_ID = 1 AND PERMISSION_ID = 100003;
DELETE FROM SYS_ROLE_PERMISSION WHERE ROLE_ID = 1 AND PERMISSION_ID = 100004;
DELETE FROM T_SYS_PERMISSION WHERE PERMISSION_ID = 100001;
DELETE FROM T_SYS_PERMISSION WHERE PERMISSION_ID = 100002;
DELETE FROM T_SYS_PERMISSION WHERE PERMISSION_ID = 100003;
DELETE FROM T_SYS_PERMISSION WHERE PERMISSION_ID = 100004;
DELETE FROM T_USER WHERE USER_ID = 1;
DELETE FROM T_SYS_ROLE WHERE ROLE_ID = 1;
INSERT INTO T_USER (USER_ID,USER_NAME,`PASSWORD`,SALT,STATE) VALUES (1,'admin','a9da90b514ec92e0973212c868408c79','root',1);
INSERT INTO T_SYS_ROLE (ROLE_ID,DESCRIPTION,IS_DEL,ROLE) VALUES (1,'',0,'超级管理员');
INSERT INTO SYS_USER_ROLE(USER_ID,ROLE_ID) VALUES (1,1);
INSERT INTO T_SYS_PERMISSION(PERMISSION_ID,ANCESTOR_IDS,AVAILABLE,`NAME`,PARENT_ID,PERMISSION,RESOURCE_TYPE,URL) VALUES
(100001,100001,TRUE,'项目',100000,'smarto:projects:menu','menu','/projects');
INSERT INTO T_SYS_PERMISSION(PERMISSION_ID,ANCESTOR_IDS,AVAILABLE,`NAME`,PARENT_ID,PERMISSION,RESOURCE_TYPE,URL) VALUES
(100002,100002,TRUE,'创建项目',100001,'smarto:projects:create','btn',NULL);
INSERT INTO T_SYS_PERMISSION(PERMISSION_ID,ANCESTOR_IDS,AVAILABLE,`NAME`,PARENT_ID,PERMISSION,RESOURCE_TYPE,URL) VALUES
(100003,100003,TRUE,'删除项目',100001,'smarto:projects:delete','btn',NULL);
INSERT INTO T_SYS_PERMISSION(PERMISSION_ID,ANCESTOR_IDS,AVAILABLE,`NAME`,PARENT_ID,PERMISSION,RESOURCE_TYPE,URL) VALUES
(100004,100004,TRUE,'管理项目',100001,'smarto:projects:manage','btn',NULL);
INSERT INTO SYS_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1,100001);
INSERT INTO SYS_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1,100003);
INSERT INTO SYS_ROLE_PERMISSION (ROLE_ID,PERMISSION_ID) VALUES (1,100004);


